// src/lib/assessment/questions.ts
import type { Question, AssessmentLevel } from "../../types";

// Bank soal per skillId dan level
const BANK: Record<string, Record<AssessmentLevel, Question[]>> = {
  javascript: {
    Beginner: [
      {
        id: "js-1",
        question: "Which method adds an element to the end of an array?",
        options: ["push()", "pop()", "shift()", "unshift()"],
        correct: 0,
        category: "javascript",
        level: "Beginner",
      },
      {
        id: "js-2",
        question: "What is the result of `typeof NaN`?",
        options: ["'number'", "'NaN'", "'undefined'", "'object'"],
        correct: 0,
        category: "javascript",
        level: "Beginner",
      },
      {
        id: "js-3",
        question: "Which operator checks both value and type equality?",
        options: ["==", "===", "!=", ">="],
        correct: 1,
        category: "javascript",
        level: "Beginner",
      },
      {
        id: "js-4",
        question: "What does Array.prototype.map() return?",
        options: [
          "A new array",
          "The sum of elements",
          "A single boolean",
          "The original array modified",
        ],
        correct: 0,
        category: "javascript",
        level: "Beginner",
      },
      {
        id: "js-5",
        question: "Which keyword creates a block-scoped variable?",
        options: ["var", "let", "function", "with"],
        correct: 1,
        category: "javascript",
        level: "Beginner",
      },
      {
        id: "js-6",
        question: "In arrow functions, 'this' is bound to...",
        options: [
          "the surrounding (lexical) scope",
          "a new object",
          "the global object",
          "undefined always",
        ],
        correct: 0,
        category: "javascript",
        level: "Beginner",
      },
      {
        id: "js-7",
        question: "Which Promise method runs regardless of fulfillment or rejection?",
        options: ["then", "catch", "finally", "all"],
        correct: 2,
        category: "javascript",
        level: "Beginner",
      },
      {
        id: "js-8",
        question: "In a function parameter list, what does `...args` represent?",
        options: ["Spread syntax", "Rest parameter", "Gather operator", "Varargs"],
        correct: 1,
        category: "javascript",
        level: "Beginner",
      },
      {
        id: "js-9",
        question: "Which method converts a JSON string to an object?",
        options: ["JSON.parse", "JSON.stringify", "toJSON", "parseJSON"],
        correct: 0,
        category: "javascript",
        level: "Beginner",
      },
      {
        id: "js-10",
        question: "Which method removes the last element of an array?",
        options: ["pop()", "shift()", "slice()", "map()"],
        correct: 0,
        category: "javascript",
        level: "Beginner",
      },
    ],
    Intermediate: [
      { id: "js-11", question: "What is a closure in JavaScript?", options: ["A function with access to its outer function's scope even after the outer function has returned", "A method for closing a web page", "A special type of class", "An object that stores data"], correct: 0, category: "javascript", level: "Intermediate" },
      { id: "js-12", question: "What is event bubbling?", options: ["A way to call functions recursively", "A function that automatically returns true or false", "The propagation of an event from an element up through its ancestors", "A method to prevent event propagation"], correct: 2, category: "javascript", level: "Intermediate" },
      { id: "js-13", question: "What is the purpose of `Object.keys()`?", options: ["To return an array of a given object's own enumerable property names", "To check if an object is empty", "To count the number of keys in an object", "To get the value of a key"], correct: 0, category: "javascript", level: "Intermediate" },
      { id: "js-14", question: "What is a 'IIFE'?", options: ["Immediately Invoked Function Expression", "Important Initial Function Element", "Iterative Indexed Function Evaluation", "Inline Interactive Form Engine"], correct: 0, category: "javascript", level: "Intermediate" },
      { id: "js-15", question: "What is `async/await` an extension of?", options: ["Promises", "Callbacks", "Functions", "Objects"], correct: 0, category: "javascript", level: "Intermediate" },
      { id: "js-16", question: "How do you check if a variable is an array?", options: ["`Array.isArray(myVar)`", "`typeof myVar === 'array'`", "`myVar.isArray`", "`is_array(myVar)`"], correct: 0, category: "javascript", level: "Intermediate" },
      { id: "js-17", question: "What is the result of `[1, 2, 3] + [4, 5, 6]`?", options: ["`'1,2,34,5,6'`", "`[1, 2, 3, 4, 5, 6]`", "`'123456'`", "Syntax Error"], correct: 0, category: "javascript", level: "Intermediate" },
      { id: "js-18", question: "What is the use of `StrictMode`?", options: ["To enforce stricter parsing and error handling", "To make code run faster", "To disable certain features", "To automatically fix code errors"], correct: 0, category: "javascript", level: "Intermediate" },
      { id: "js-19", question: "What is the difference between `let` and `const`?", options: ["`let` can be reassigned, `const` cannot", "`const` is global, `let` is not", "`let` is block-scoped, `const` is function-scoped", "They are the same"], correct: 0, category: "javascript", level: "Intermediate" },
      { id: "js-20", question: "Which method is used to remove a property from an object?", options: ["`delete`", "`remove()`", "`pop()`", "`splice()`"], correct: 0, category: "javascript", level: "Intermediate" },
    ],
    Advanced: [
      { id: "js-21", question: "Explain the `prototype` chain in JavaScript.", options: ["A mechanism for inheritance in objects", "A series of function calls", "A way to link HTML elements", "A method for code execution"], correct: 0, category: "javascript", level: "Advanced" },
      { id: "js-22", question: "What is the `Symbol` data type?", options: ["A unique and immutable primitive value", "A way to create comments", "A type used for numbers", "A special kind of array"], correct: 0, category: "javascript", level: "Advanced" },
      { id: "js-23", question: "Explain the concept of 'hoisting'.", options: ["The process where the interpreter moves variable and function declarations to the top of their scope before execution", "A way to elevate a variable to a global scope", "A type of error handling", "A method for debugging"], correct: 0, category: "javascript", level: "Advanced" },
      { id: "js-24", question: "What is a `WeakMap`?", options: ["A collection of key/value pairs where keys are weakly referenced", "A map that can only store strings", "A data structure for weak variables", "An array with limited memory"], correct: 0, category: "javascript", level: "Advanced" },
      { id: "js-25", question: "What are generators?", options: ["Functions that can be paused and resumed", "Objects that generate new classes", "A type of asynchronous function", "Functions that are only used for loops"], correct: 0, category: "javascript", level: "Advanced" },
      { id: "js-26", question: "What is the purpose of `Proxy` objects?", options: ["To define custom behavior for fundamental operations (e.g., property lookup, assignment)", "To redirect network requests", "To create a copy of an object", "To connect to a database"], correct: 0, category: "javascript", level: "Advanced" },
      { id: "js-27", question: "What is the 'call stack'?", options: ["A stack data structure that stores information about the active subroutines of a computer program", "A list of all global variables", "A way to manage network connections", "A type of memory allocation"], correct: 0, category: "javascript", level: "Advanced" },
      { id: "js-28", question: "Explain the 'event loop'.", options: ["A single-threaded loop that monitors the call stack and the message queue to push tasks onto the stack", "A method for managing network events", "A way to loop through an array", "A type of synchronous function"], correct: 0, category: "javascript", level: "Advanced" },
      { id: "js-29", question: "What is a 'Promise.allSettled'?", options: ["A Promise that returns a promise that resolves after all of the given promises have either fulfilled or rejected", "A promise that returns an array of all fulfilled promises", "A promise that returns the first promise to resolve", "A promise that returns an error"], correct: 0, category: "javascript", level: "Advanced" },
      { id: "js-30", question: "What are decorators?", options: ["Functions that take another function and extend its behavior", "A method for styling HTML elements", "A type of CSS property", "A way to organize code into modules"], correct: 0, category: "javascript", level: "Advanced" },
    ],
    Expert: [
      { id: "js-31", question: "Explain the difference between `__proto__` and `prototype`.", options: ["`__proto__` is the actual object link in the prototype chain, while `prototype` is a property on a constructor function to set the `__proto__` of instances", "They are the same", "One is for classes, the other for objects", "One is a function, the other is an object"], correct: 0, category: "javascript", level: "Expert" },
      { id: "js-32", question: "Describe V8's hidden classes.", options: ["A performance optimization used by V8 to improve property access time", "A way to hide private class methods", "A feature for creating anonymous classes", "A security feature to prevent data access"], correct: 0, category: "javascript", level: "Expert" },
      { id: "js-33", question: "How does the JavaScript engine's 'JIT' compiler work?", options: ["It compiles JavaScript code into machine code just before execution to improve performance", "It interprets code line by line", "It runs code only after the whole script is compiled", "It converts code to a different language"], correct: 0, category: "javascript", level: "Expert" },
      { id: "js-34", question: "What is `TypedArray` and when is it useful?", options: ["An array-like view of an underlying binary data buffer, useful for handling raw binary data efficiently", "A method to enforce type-checking in JavaScript", "A new data type in ES2020", "An array that can only store one data type"], correct: 0, category: "javascript", level: "Expert" },
      { id: "js-35", question: "Explain the concept of 'tail call optimization'.", options: ["A process where a function's final operation is a call to another function, allowing the engine to reuse the stack frame and prevent stack overflows", "A way to optimize recursive functions", "A method to make tail functions run faster", "An optimization for array methods"], correct: 0, category: "javascript", level: "Expert" },
      { id: "js-36", question: "Describe the 'module' system in ECMAScript 2015 (`import`/`export`).", options: ["A way to organize code into separate, reusable files with strict scope", "A method for including external scripts", "A feature for creating global variables", "A type of data encapsulation"], correct: 0, category: "javascript", level: "Expert" },
      { id: "js-37", question: "What is `Service Worker` and its use cases?", options: ["A script that your browser runs in the background, separate from a web page, enabling features like offline functionality and push notifications", "A tool for debugging web pages", "A type of server-side script", "A framework for web animations"], correct: 0, category: "javascript", level: "Expert" },
      { id: "js-38", question: "What are `WebAssembly (Wasm)`'s advantages for web development?", options: ["High performance, low-level language that can run in the browser, enabling computationally intensive tasks", "A way to make web pages more secure", "A new syntax for JavaScript", "A tool for creating animated web pages"], correct: 0, category: "javascript", level: "Expert" },
      { id: "js-39", question: "Explain the difference between `microtask` and `macrotask` queues.", options: ["`Microtasks` (like promises) are handled before the next `macrotask` (like `setTimeout`) is processed, ensuring that they run predictably and quickly after their async call", "They are the same", "One is for small tasks, the other for large ones", "One is for the browser, the other for the server"], correct: 0, category: "javascript", level: "Expert" },
      { id: "js-40", question: "What are 'closures' and what are some common pitfalls?", options: ["A function with access to its outer scope, which can lead to memory leaks if not managed correctly", "A way to close a function", "An error handling method", "A method to lock variables"], correct: 0, category: "javascript", level: "Expert" },
    ],
  },
  react: {
    Beginner: [
      { id: "react-1", question: "What is the Virtual DOM?", options: ["A lightweight copy of the DOM", "A physical component of the browser", "A programming language", "A CSS framework"], correct: 0, category: "react", level: "Beginner" },
      {
        id: "react-2",
        question: "Which hook is used for side effects?",
        options: ["useEffect", "useMemo", "useReducer", "useRef"],
        correct: 0,
        category: "react",
        level: "Beginner",
      },
      {
        id: "react-3",
        question: "What does useState return?",
        options: ["Only the current state", "Only a setter function", "A pair: [state, setState]", "A function that triggers re-render only"],
        correct: 2,
        category: "react",
        level: "Beginner",
      },
      {
        id: "react-4",
        question: "Why are 'key' props important when rendering lists?",
        options: ["They help React identify items for efficient updates", "They add automatic ordering", "They apply default styles", "They force components to re-render"],
        correct: 0,
        category: "react",
        level: "Beginner",
      },
      {
        id: "react-5",
        question: "A controlled component is...",
        options: ["An input whose value is controlled by React state", "A form that manages its own state in the DOM", "Any component using useRef", "A server component"],
        correct: 0,
        category: "react",
        level: "Beginner",
      },
      {
        id: "react-6",
        question: "useMemo is primarily used to...",
        options: ["Memoize the result of an expensive calculation", "Manage side effects", "Store mutable values without re-render", "Schedule state updates"],
        correct: 0,
        category: "react",
        level: "Beginner",
      },
      {
        id: "react-7",
        question: "Which hook consumes a value from React Context?",
        options: ["useReducer", "useContext", "useId", "useLayoutEffect"],
        correct: 1,
        category: "react",
        level: "Beginner",
      },
      {
        id: "react-8",
        question: "A common use of useRef is to...",
        options: ["Store a mutable value without causing a re-render", "Trigger state updates", "Fetch remote data", "Memoize derived values"],
        correct: 0,
        category: "react",
        level: "Beginner",
      },
      {
        id: "react-9",
        question: "What does an empty dependency array ([]) mean in useEffect?",
        options: ["Run once after the first render", "Run after every render", "Never run", "Run only on unmount"],
        correct: 0,
        category: "react",
        level: "Beginner",
      },
      {
        id: "react-10",
        question: "What is JSX?",
        options: ["A JavaScript syntax extension for describing UI", "A JSON variant", "A templating engine unrelated to JavaScript", "A CSS preprocessor"],
        correct: 0,
        category: "react",
        level: "Beginner",
      },
    ],
    Intermediate: [
      { id: "react-11", question: "What is `useCallback` used for?", options: ["To prevent a function from being re-created on every render", "To perform a side effect", "To manage state in functional components", "To fetch data from an API"], correct: 0, category: "react", level: "Intermediate" },
      { id: "react-12", question: "What is a React custom hook?", options: ["A function that uses other React hooks and allows for reusable stateful logic", "A built-in hook provided by React", "A component that uses hooks", "A library for React hooks"], correct: 0, category: "react", level: "Intermediate" },
      { id: "react-13", question: "Explain component composition.", options: ["Building complex components by combining simpler ones", "Creating a new component with a class", "Using multiple hooks in one component", "A method for styling components"], correct: 0, category: "react", level: "Intermediate" },
      { id: "react-14", question: "When should you use `useReducer` instead of `useState`?", options: ["When you have complex state logic that involves multiple sub-values", "For simple state management", "When you need to make API calls", "When you want to prevent re-renders"], correct: 0, category: "react", level: "Intermediate" },
      { id: "react-15", question: "What is `lifting state up`?", options: ["Moving the state from a child component to its parent component", "Moving state from a class component to a functional component", "A method for passing props down", "A way to manage global state"], correct: 0, category: "react", level: "Intermediate" },
      { id: "react-16", question: "What is `React.Fragment`?", options: ["A component that lets you group a list of children without adding extra nodes to the DOM", "A way to create a reusable component", "A method to handle errors", "A component for routing"], correct: 0, category: "react", level: "Intermediate" },
      { id: "react-17", question: "What is the purpose of `useLayoutEffect`?", options: ["To perform side effects synchronously after the DOM has been mutated but before the browser has painted", "To handle asynchronous operations", "To manage component state", "To optimize performance"], correct: 0, category: "react", level: "Intermediate" },
      { id: "react-18", question: "What are `props.children`?", options: ["A special prop that represents the children passed to a component", "A way to get all the props of a component", "A method to handle state", "A way to access the parent component"], correct: 0, category: "react", level: "Intermediate" },
      { id: "react-19", question: "What is a `pure component`?", options: ["A component that only re-renders when its props or state change", "A component with no state", "A component with no props", "A component with no side effects"], correct: 0, category: "react", level: "Intermediate" },
      { id: "react-20", question: "What is the primary function of `useMemo`?", options: ["To memoize the value of a function's return, preventing re-computation on every render", "To handle side effects", "To manage component state", "To create a custom hook"], correct: 0, category: "react", level: "Intermediate" },
    ],
    Advanced: [
      { id: "react-21", question: "Explain the `reconciliation` process in React.", options: ["The process of comparing the old and new virtual DOM to find the most efficient way to update the real DOM", "A method for resolving state conflicts", "A type of server-side rendering", "A way to handle asynchronous data"], correct: 0, category: "react", level: "Advanced" },
      { id: "react-22", question: "What is the `Suspense` component used for?", options: ["To handle loading states for components that are being lazy-loaded or are fetching data asynchronously", "To manage global state", "To optimize component rendering", "To lazy-load images"], correct: 0, category: "react", level: "Advanced" },
      { id: "react-23", question: "What is a `Higher-Order Component` (HOC)?", options: ["A function that takes a component as an argument and returns a new component with enhanced functionality", "A component that renders other components", "A hook for state management", "A component with multiple props"], correct: 0, category: "react", level: "Advanced" },
      { id: "react-24", question: "How do you handle a `side effect` that needs to clean up after itself?", options: ["By returning a cleanup function from the `useEffect` hook", "By using a separate `cleanUpEffect` hook", "By using `componentWillUnmount`", "By calling `setState` with a null value"], correct: 0, category: "react", level: "Advanced" },
      { id: "react-25", question: "What is `useRef`'s primary use case?", options: ["To get a mutable value that persists across renders without causing a re-render", "To manage component state", "To perform side effects", "To optimize performance"], correct: 0, category: "react", level: "Advanced" },
      { id: "react-26", question: "Explain the `Context API`'s purpose.", options: ["To provide a way to pass data through the component tree without having to pass props down manually at every level", "To manage component state", "To handle server-side rendering", "To create a new component"], correct: 0, category: "react", level: "Advanced" },
      { id: "react-27", question: "What is the difference between `useEffect` and `useLayoutEffect`?", options: ["`useEffect` runs after the browser has painted, while `useLayoutEffect` runs synchronously before the browser has painted", "They are the same", "One is for class components, the other for functional components", "One is for managing state, the other for side effects"], correct: 0, category: "react", level: "Advanced" },
      { id: "react-28", question: "What is the purpose of `React.memo`?", options: ["To prevent a component from re-rendering if its props have not changed", "To manage a component's state", "To handle side effects", "To create a new component"], correct: 0, category: "react", level: "Advanced" },
      { id: "react-29", question: "What are `Render Props`?", options: ["A technique for sharing code between React components using a prop whose value is a function", "A way to pass data between components", "A method to handle state", "A way to style components"], correct: 0, category: "react", level: "Advanced" },
      { id: "react-30", question: "What is a `key` prop and why is it important?", options: ["A unique string attribute you should include when creating list of elements, as it helps React identify which items have changed, are added, or are removed", "A prop that stores a unique key for a component", "A prop for handling security", "A prop for sorting components"], correct: 0, category: "react", level: "Advanced" },
    ],
    Expert: [
      { id: "react-31", question: "Explain the `Fiber` reconciliation algorithm.", options: ["A new reconciliation algorithm that enables incremental rendering, allowing React to pause and resume rendering to avoid blocking the browser", "A method for handling CSS animations", "A way to manage state in React", "A tool for debugging React applications"], correct: 0, category: "react", level: "Expert" },
      { id: "react-32", question: "Describe the concept of 'concurrent mode'.", options: ["A set of new features that allows React to work on multiple state updates at the same time, prioritizing high-priority updates like user input", "A feature that allows multiple users to edit a document at the same time", "A mode for running React on multiple servers", "A new type of state management"], correct: 0, category: "react", level: "Expert" },
      { id: "react-33", question: "What is `React.lazy()` and `Suspense` used for?", options: ["To code-split React components and lazy-load them on demand, improving initial load time", "To manage component state", "To handle asynchronous data", "To optimize performance of all components"], correct: 0, category: "react", level: "Expert" },
      { id: "react-34", question: "Explain the benefits of `SSR` (Server-Side Rendering) in React.", options: ["Improved performance for users with slow network connections, better SEO, and faster time-to-content", "It only works on the server", "It's a way to handle state management", "It's a method for debugging"], correct: 0, category: "react", level: "Expert" },
      { id: "react-35", question: "What is `hydration` in React?", options: ["The process of attaching event listeners to the server-side rendered HTML after it's loaded on the client", "A way to handle state updates", "A method for fetching data", "A process to improve a component's performance"], correct: 0, category: "react", level: "Expert" },
      { id: "react-36", question: "What is `Memoization` in React?", options: ["An optimization technique used to cache the result of a function or component rendering, preventing re-computation if the inputs are the same", "A way to handle side effects", "A method for passing data between components", "A type of state management"], correct: 0, category: "react", level: "Expert" },
      { id: "react-37", question: "What are the common causes of `re-renders` in React and how do you prevent them?", options: ["State or prop changes; prevent with `React.memo`, `useMemo`, and `useCallback`", "Using too many components", "Making too many API calls", "Using class components"], correct: 0, category: "react", level: "Expert" },
      { id: "react-38", question: "What is the difference between `props` and `state`?", options: ["`Props` are immutable and passed down from a parent component, while `state` is mutable and managed within a component", "They are the same", "One is for class components, the other for functional components", "One is for data, the other for functions"], correct: 0, category: "react", level: "Expert" },
      { id: "react-39", question: "What is the significance of the `key` prop in React lists?", options: ["Keys help React identify which items have changed, are added, or are removed. This helps React with its reconciliation process and prevents bugs.", "Keys are used for styling components", "Keys are used for passing data between components", "Keys are used for security"], correct: 0, category: "react", level: "Expert" },
      { id: "react-40", question: "How do you handle error boundaries in React?", options: ["By using a class component with a `componentDidCatch` or `getDerivedStateFromError` method", "By using a special hook", "By using a `try/catch` block", "By using a `finally` block"], correct: 0, category: "react", level: "Expert" },
    ],
  },
  python: {
    Beginner: [
      {
        id: "py-1",
        question: "Which library is commonly used for data manipulation?",
        options: ["NumPy", "Pandas", "Matplotlib", "All of the above"],
        correct: 3,
        category: "python",
        level: "Beginner",
      },
      {
        id: "py-2",
        question: "What keyword defines a function in Python?",
        options: ["func", "def", "function", "lambda"],
        correct: 1,
        category: "python",
        level: "Beginner",
      },
      {
        id: "py-3",
        question: "What does a list comprehension produce?",
        options: ["A new list", "A generator", "A tuple", "A set"],
        correct: 0,
        category: "python",
        level: "Beginner",
      },
      {
        id: "py-4",
        question: "Which file mode opens a text file for reading?",
        options: ["'r'", "'w'", "'a'", "'x'"],
        correct: 0,
        category: "python",
        level: "Beginner",
      },
      {
        id: "py-5",
        question: "What does len({a:1, b:2}) evaluate to in Python?",
        options: ["1", "2", "3", "Raises an error"],
        correct: 1,
        category: "python",
        level: "Beginner",
      },
      {
        id: "py-6",
        question: "Which keyword creates an anonymous function?",
        options: ["anon", "lambda", "def", "func"],
        correct: 1,
        category: "python",
        level: "Beginner",
      },
      {
        id: "py-7",
        question: "Which tool installs Python packages from PyPI?",
        options: ["pip", "conda", "make", "brew"],
        correct: 0,
        category: "python",
        level: "Beginner",
      },
      {
        id: "py-8",
        question: "What do *args and **kwargs represent?",
        options: [
          "Positional args and keyword args",
          "Lists and dicts",
          "Required and optional args",
          "Local and global vars",
        ],
        correct: 0,
        category: "python",
        level: "Beginner",
      },
      {
        id: "py-9",
        question: "Which operator checks object identity (same object in memory)?",
        options: ["==", "is", "in", "!="],
        correct: 1,
        category: "python",
        level: "Beginner",
      },
      {
        id: "py-10",
        question: "What does my_list[::-1] return?",
        options: [
          "A reversed copy of the list",
          "The list sorted ascending",
          "Every other element",
          "An in-place reversal",
        ],
        correct: 0,
        category: "python",
        level: "Beginner",
      },
    ],
    Intermediate: [
      { id: "py-11", question: "What is a 'decorator' in Python?", options: ["A function that takes another function and extends its behavior without explicitly modifying it", "A way to style a function", "A method for debugging", "A special type of class"], correct: 0, category: "python", level: "Intermediate" },
      { id: "py-12", question: "What is a 'generator'?", options: ["A function that returns an iterator, producing one value at a time", "A tool for generating code", "A class that creates objects", "A method for handling loops"], correct: 0, category: "python", level: "Intermediate" },
      { id: "py-13", question: "What is the purpose of the `__init__` method?", options: ["To initialize a new instance of a class", "To start a program", "To define a new function", "To import a library"], correct: 0, category: "python", level: "Intermediate" },
      { id: "py-14", question: "What is a 'docstring'?", options: ["A string literal that occurs as the first statement in a module, function, class, or method definition", "A type of comment", "A string used for documentation", "A way to add a new line"], correct: 0, category: "python", level: "Intermediate" },
      { id: "py-15", question: "What is `if __name__ == '__main__'` used for?", options: ["To ensure the code inside only runs when the script is executed directly", "To define the main function", "To check if the script is running", "To import all functions"], correct: 0, category: "python", level: "Intermediate" },
      { id: "py-16", question: "What is the difference between a list and a tuple?", options: ["Lists are mutable, tuples are immutable", "Lists are faster than tuples", "Tuples are for storing strings, lists are for numbers", "They are the same"], correct: 0, category: "python", level: "Intermediate" },
      { id: "py-17", question: "What is a 'set' in Python?", options: ["An unordered collection of unique elements", "A list of unique elements", "A dictionary of unique keys", "A way to store data"], correct: 0, category: "python", level: "Intermediate" },
      { id: "py-18", question: "What is the purpose of the `try...except` block?", options: ["To handle exceptions and errors gracefully", "To check for a value", "To define a new function", "To loop through a list"], correct: 0, category: "python", level: "Intermediate" },
      { id: "py-19", question: "How do you read a CSV file using the `pandas` library?", options: ["`pd.read_csv()`", "`read_file()`", "`load_csv()`", "`import_csv()`"], correct: 0, category: "python", level: "Intermediate" },
      { id: "py-20", question: "What is a 'virtual environment'?", options: ["A self-contained directory tree that contains a Python installation for a particular project", "A way to run a program on a virtual machine", "A tool for creating virtual servers", "A method for debugging"], correct: 0, category: "python", level: "Intermediate" },
    ],
    Advanced: [
      { id: "py-21", question: "Explain 'metaclasses' in Python.", options: ["The class of a class, which defines how a class itself is created", "A type of class", "A method for creating a class", "A way to inherit from multiple classes"], correct: 0, category: "python", level: "Advanced" },
      { id: "py-22", question: "What is 'GIL'?", options: ["Global Interpreter Lock, which allows only one thread to execute at a time in CPython", "Global Import Library", "General Interactive Language", "Graphical Interface Layer"], correct: 0, category: "python", level: "Advanced" },
      { id: "py-23", question: "How do you perform 'asynchronous' I/O in Python?", options: ["Using the `asyncio` library with `async`/`await` keywords", "Using the `threading` library", "By writing multithreaded code", "Using callbacks"], correct: 0, category: "python", level: "Advanced" },
      { id: "py-24", question: "What is 'monkey patching'?", options: ["Dynamically modifying a class or module at runtime", "A method for fixing bugs", "A way to create a patch file", "A type of code injection"], correct: 0, category: "python", level: "Advanced" },
      { id: "py-25", question: "Explain a 'descriptor'.", options: ["An object attribute with 'binding behavior', whose attribute access has been overridden by methods in the descriptor protocol", "A way to describe a class", "A method for creating a function", "A type of documentation"], correct: 0, category: "python", level: "Advanced" },
      { id: "py-26", question: "What are 'coroutine'?", options: ["A type of function that can be paused and resumed, used for asynchronous programming", "A method for multithreading", "A way to create a new function", "A type of loop"], correct: 0, category: "python", level: "Advanced" },
      { id: "py-27", question: "What is the `__slots__` attribute?", options: ["To explicitly declare data members (instance variables), preventing the creation of `__dict__` and saving memory", "A way to define a class's attributes", "A method for creating new objects", "A type of class method"], correct: 0, category: "python", level: "Advanced" },
      { id: "py-28", question: "Explain the `MRO` (Method Resolution Order).", options: ["The order in which Python searches for inherited methods in a class hierarchy", "A way to resolve errors in a program", "A method for organizing code", "A tool for debugging"], correct: 0, category: "python", level: "Advanced" },
      { id: "py-29", question: "What is the purpose of `Weak references`?", options: ["To hold a reference to an object without preventing its garbage collection", "To create a weak connection to a server", "To store data in a weak variable", "To manage memory"], correct: 0, category: "python", level: "Advanced" },
      { id: "py-30", question: "What is `type hinting`?", options: ["A way to provide function and variable type information to static analysis tools", "A method for creating new data types", "A type of comment", "A way to debug a program"], correct: 0, category: "python", level: "Advanced" },
    ],
    Expert: [
      { id: "py-31", question: "Describe how Python manages memory.", options: ["It uses a private heap for all objects and a garbage collector with reference counting and a generational garbage collection algorithm to manage unused objects", "It uses the system's memory", "It has no garbage collector", "It uses a public memory pool"], correct: 0, category: "python", level: "Expert" },
      { id: "py-32", question: "Explain the concept of `Duck Typing`.", options: ["A programming style that relies on an object's behavior rather than its explicit class or interface", "A way to create a new class", "A method for inheritance", "A type of design pattern"], correct: 0, category: "python", level: "Expert" },
      { id: "py-33", question: "How does `multiprocessing` overcome the GIL?", options: ["By using separate processes, each with its own Python interpreter and memory space, so the GIL does not block other processes", "It doesn't", "It uses threads", "It is an alternative to Python"], correct: 0, category: "python", level: "Expert" },
      { id: "py-34", question: "What is a 'context manager' and how do you implement one?", options: ["An object that defines the runtime context to be established when executing a `with` statement, implemented using `__enter__` and `__exit__` methods", "A way to manage a function's context", "A method for handling exceptions", "A tool for debugging"], correct: 0, category: "python", level: "Expert" },
      { id: "py-35", question: "What is a `F-string`?", options: ["A string literal prefixed with 'f' that allows for easy string formatting with expressions inside braces", "A function that formats a string", "A new data type in Python", "A way to create a new string"], correct: 0, category: "python", level: "Expert" },
      { id: "py-36", question: "What is the purpose of `mypy`?", options: ["A static type checker that helps find bugs in your code by analyzing type hints", "A tool for code formatting", "A linter for Python", "A package manager"], correct: 0, category: "python", level: "Expert" },
      { id: "py-37", question: "Explain the 'observer' design pattern.", options: ["A software design pattern in which an object, called the subject, maintains a list of its dependents, called observers, and notifies them automatically of any state changes", "A way to observe a program's behavior", "A method for debugging", "A tool for testing code"], correct: 0, category: "python", level: "Expert" },
      { id: "py-38", question: "What is a `named tuple`?", options: ["A subclass of a tuple that allows for a more readable and self-documenting code", "A new data type", "A tuple with a name", "A way to create a tuple"], correct: 0, category: "python", level: "Expert" },
      { id: "py-39", question: "What is a 'factory function'?", options: ["A function that creates and returns new objects", "A method for creating a class", "A way to handle multiple functions", "A tool for debugging"], correct: 0, category: "python", level: "Expert" },
      { id: "py-40", question: "Explain the `Decorator` design pattern.", options: ["A structural design pattern that allows adding new behaviors to objects dynamically by placing them inside special wrapper objects", "A way to style a function", "A method for debugging", "A type of class"], correct: 0, category: "python", level: "Expert" },
    ],
  },
  design: {
    Beginner: [
      {
        id: "design-1",
        question: "What is the primary purpose of a wireframe?",
        options: [
          "Show structure/layout without visual detail",
          "Define brand voice",
          "Test server performance",
          "Export production assets",
        ],
        correct: 0,
        category: "design",
        level: "Beginner",
      },
      {
        id: "design-2",
        question: "Which color model is standard for digital screens?",
        options: ["RGB", "CMYK", "Pantone", "RYB"],
        correct: 0,
        category: "design",
        level: "Beginner",
      },
      {
        id: "design-3",
        question: "The main goal of contrast in UI is to...",
        options: [
          "Establish visual hierarchy and readability",
          "Make designs more colorful",
          "Reduce whitespace",
          "Ensure brand consistency only",
        ],
        correct: 0,
        category: "design",
        level: "Beginner",
      },
      {
        id: "design-4",
        question: "A user persona is...",
        options: [
          "A fictional archetype based on research",
          "A real individual tester",
          "A stakeholder map",
          "A UI style guide",
        ],
        correct: 0,
        category: "design",
        level: "Beginner",
      },
      {
        id: "design-5",
        question: "In usability testing, the think-aloud method helps to...",
        options: [
          "Reveal users' reasoning in real time",
          "Measure heart rate",
          "Require a large sample size",
          "Eliminate all bias",
        ],
        correct: 0,
        category: "design",
        level: "Beginner",
      },
      {
        id: "design-6",
        question: "Responsive design means...",
        options: [
          "Layouts adapt to different screen sizes",
          "Only mobile screens are supported",
          "Using CSS frameworks only",
          "Scaling images to 2x",
        ],
        correct: 0,
        category: "design",
        level: "Beginner",
      },
    ],
    Intermediate: [
      { id: "design-11", question: "What is a 'design system'?", options: ["A complete set of design standards, documentation, and components to manage design at scale", "A new design tool", "A method for designing a user interface", "A way to organize files"], correct: 0, category: "design", level: "Intermediate" },
      { id: "design-12", question: "What is the difference between a `wireframe` and a `prototype`?", options: ["A wireframe is a low-fidelity layout, while a prototype is an interactive simulation of the final product", "A prototype is a high-fidelity design, while a wireframe is a low-fidelity one", "They are the same", "A wireframe is for the web, a prototype is for mobile"], correct: 0, category: "design", level: "Intermediate" },
      { id: "design-13", question: "What is `Gestalt psychology`?", options: ["A school of thought in design that states the whole is greater than the sum of its parts", "A method for user research", "A way to design a user interface", "A type of color theory"], correct: 0, category: "design", level: "Intermediate" },
      { id: "design-14", question: "What is the purpose of `A/B testing` in design?", options: ["To compare two versions of a design to see which performs better with users", "To test the security of a design", "To analyze a design's aesthetics", "To test a design on multiple platforms"], correct: 0, category: "design", level: "Intermediate" },
      { id: "design-15", question: "What is a `style guide`?", options: ["A document that outlines a company's visual identity, including colors, typography, and logos", "A book on fashion", "A set of rules for writing code", "A tool for creating a website"], correct: 0, category: "design", level: "Intermediate" },
      { id: "design-16", question: "What is 'information architecture'?", options: ["The structural design of shared information environments; organizing, labeling, and structuring content to make it understandable and findable", "A type of database design", "A method for building websites", "A way to organize files"], correct: 0, category: "design", level: "Intermediate" },
      { id: "design-17", question: "What is a `user journey map`?", options: ["A diagram that visualizes the steps a user takes to achieve a goal with a product", "A map of a user's location", "A way to track a user's activity", "A tool for project management"], correct: 0, category: "design", level: "Intermediate" },
      { id: "design-18", question: "What is `card sorting`?", options: ["A user research method where participants group a set of cards into categories that make sense to them", "A way to organize a deck of cards", "A method for creating a card game", "A tool for managing tasks"], correct: 0, category: "design", level: "Intermediate" },
      { id: "design-19", question: "What is a `heuristic evaluation`?", options: ["A usability inspection method where experts evaluate a product's interface based on a set of usability principles", "A way to evaluate a user's behavior", "A method for testing a product's performance", "A tool for debugging"], correct: 0, category: "design", level: "Intermediate" },
      { id: "design-20", question: "What is `microcopy`?", options: ["Small pieces of text in a UI that guide the user, such as button labels, error messages, and form field hints", "A type of font", "A way to write a document", "A tool for managing text"], correct: 0, category: "design", level: "Intermediate" },
    ],
    Advanced: [
      { id: "design-21", question: "Explain `Fitts's Law`.", options: ["A model predicting the time required to move to a target area, as a function of the distance to the target and the size of the target", "A principle of motion graphics", "A law of physics", "A rule for typography"], correct: 0, category: "design", level: "Advanced" },
      { id: "design-22", question: "What is `Hick's Law`?", options: ["The time it takes for a person to make a decision is a function of the number of choices available", "A law of physics", "A rule for user interface design", "A method for user research"], correct: 0, category: "design", level: "Advanced" },
      { id: "design-23", question: "Explain the `Golden Ratio` in design.", options: ["A mathematical ratio (approx. 1.618) that is often used in art and design to create aesthetically pleasing compositions", "A rule for typography", "A way to measure a product's success", "A method for color theory"], correct: 0, category: "design", level: "Advanced" },
      { id: "design-24", question: "What is `Progressive Enhancement`?", options: ["A strategy for web design that emphasizes core content and functionality first, then adds more complex features as a user's browser allows", "A way to improve a product's performance", "A method for building a website", "A tool for debugging"], correct: 0, category: "design", level: "Advanced" },
      { id: "design-25", question: "What is the purpose of `Lean UX`?", options: ["To focus on the user experience in an agile, rapid, and iterative way, prioritizing outcomes over deliverables", "A method for designing a user interface", "A tool for managing tasks", "A way to organize files"], correct: 0, category: "design", level: "Advanced" },
      { id: "design-26", question: "What are `Affinities` in UX?", options: ["Thematic groupings of data gathered during user research, used to identify key insights and patterns", "A way to describe a user's preferences", "A method for user research", "A tool for project management"], correct: 0, category: "design", level: "Advanced" },
      { id: "design-27", question: "What is `Information Foraging Theory`?", options: ["A theory that describes how users navigate, search, and find information in a way that minimizes effort", "A way to organize information", "A method for user research", "A tool for debugging"], correct: 0, category: "design", level: "Advanced" },
      { id: "design-28", question: "What is the difference between `UI` and `UX`?", options: ["UI is the user interface (the look and feel), while UX is the overall user experience (how it feels to use the product)", "They are the same", "One is for the web, the other is for mobile", "One is for design, the other is for code"], correct: 0, category: "design", level: "Advanced" },
      { id: "design-29", question: "What is a `heuristic`?", options: ["A simple, efficient rule of thumb that helps people make decisions or solve problems more quickly", "A complex algorithm", "A method for debugging", "A type of data structure"], correct: 0, category: "design", level: "Advanced" },
      { id: "design-30", question: "What is `cognitive load`?", options: ["The total amount of mental effort being used in a person's working memory", "The time it takes for a user to make a decision", "A way to measure a user's attention", "A type of design principle"], correct: 0, category: "design", level: "Advanced" },
    ],
    Expert: [
      { id: "design-31", question: "Explain the `Double Diamond` design process model.", options: ["A four-phase model (Discover, Define, Develop, Deliver) used to structure design projects, from initial problem discovery to final solution delivery", "A method for designing a logo", "A way to manage a design team", "A tool for project management"], correct: 0, category: "design", level: "Expert" },
      { id: "design-32", question: "What is `Atomic Design`?", options: ["A methodology for creating design systems by breaking down components into their smallest parts (atoms, molecules, organisms, templates, and pages)", "A method for building a website", "A way to organize files", "A type of animation"], correct: 0, category: "design", level: "Expert" },
      { id: "design-33", question: "What is the purpose of a `heuristic analysis`?", options: ["To find usability problems in a product without involving end users", "To test a product's performance", "To analyze a product's aesthetics", "To conduct a user survey"], correct: 0, category: "design", level: "Expert" },
      { id: "design-34", question: "Explain the `usability principles` by Jakob Nielsen.", options: ["A set of ten general principles for user interface design, including `visibility of system status` and `match between system and the real world`", "A set of rules for typography", "A list of best practices for color theory", "A guide for project management"], correct: 0, category: "design", level: "Expert" },
      { id: "design-35", question: "What is `cognitive walkthrough`?", options: ["A usability inspection method where an expert walks through a user's tasks to identify potential usability problems", "A method for user research", "A tool for debugging", "A way to organize information"], correct: 0, category: "design", level: "Expert" },
      { id: "design-36", question: "What is `accessibility` in UX design?", options: ["The practice of making a website or application usable by as many people as possible, including those with disabilities", "A way to make a product more appealing", "A method for user research", "A tool for testing"], correct: 0, category: "design", level: "Expert" },
      { id: "design-37", question: "Explain the `lean startup` methodology in the context of UX.", options: ["A process of creating a product with a feedback loop of 'build-measure-learn' to validate assumptions and reduce waste", "A way to manage a design team", "A method for project management", "A tool for debugging"], correct: 0, category: "design", level: "Expert" },
      { id: "design-38", question: "What is the difference between `affordance` and `signifier`?", options: ["`Affordance` is the perceived properties of an object that suggest how it can be used, while `signifier` is a visible clue that tells a user what to do", "They are the same", "One is for UI, the other for UX", "One is a physical object, the other is a digital one"], correct: 0, category: "design", level: "Expert" },
      { id: "design-39", question: "What is the `paradigm` of `human-centered design`?", options: ["An iterative design process in which designers focus on users and their needs in each phase of the process", "A way to design a user interface", "A method for user research", "A tool for project management"], correct: 0, category: "design", level: "Expert" },
      { id: "design-40", question: "What is a `design critique`?", options: ["A structured conversation where designers give and receive feedback to improve a design", "A way to criticize a design", "A method for user research", "A tool for debugging"], correct: 0, category: "design", level: "Expert" },
    ],
  },
  marketing: {
    Beginner: [
      {
        id: "marketing-1",
        question: "What is the purpose of A/B testing?",
        options: [
          "Compare two variants to see which performs better",
          "Increase traffic instantly",
          "Replace qualitative research",
          "Eliminate seasonality",
        ],
        correct: 0,
        category: "marketing",
        level: "Beginner",
      },
      {
        id: "marketing-2",
        question: "CTA stands for...",
        options: [
          "Call To Action",
          "Content Trend Analysis",
          "Customer Trust Audit",
          "Click Through Average",
        ],
        correct: 0,
        category: "marketing",
        level: "Beginner",
      },
      {
        id: "marketing-3",
        question: "Organic traffic refers to...",
        options: [
          "Visitors from unpaid search results",
          "Traffic from paid ads",
          "Referral traffic only",
          "Direct traffic only",
        ],
        correct: 0,
        category: "marketing",
        level: "Beginner",
      },
      {
        id: "marketing-4",
        question: "CTR (Click-Through Rate) measures...",
        options: [
          "Clicks divided by impressions",
          "Purchases divided by sessions",
          "Revenue per visitor",
          "Bounce rate",
        ],
        correct: 0,
        category: "marketing",
        level: "Beginner",
      },
      {
        id: "marketing-5",
        question: "STP in marketing stands for...",
        options: [
          "Segmentation, Targeting, Positioning",
          "Sales, Traffic, Profit",
          "Strategy, Tactics, Planning",
          "Search, Tagging, Promotion",
        ],
        correct: 0,
        category: "marketing",
        level: "Beginner",
      },
      {
        id: "marketing-6",
        question: "Which is a common funnel order?",
        options: [
          "Awareness → Consideration → Conversion → Retention",
          "Conversion → Awareness → Retention → Consideration",
          "Consideration → Retention → Awareness → Conversion",
          "Retention → Conversion → Awareness → Consideration",
        ],
        correct: 0,
        category: "marketing",
        level: "Beginner",
      },
    ],
    Intermediate: [
      { id: "marketing-11", question: "What is the purpose of a 'customer journey map'?", options: ["To visualize the entire process of a customer's experience with a product or service", "A map of a customer's location", "A tool for project management", "A method for user research"], correct: 0, category: "marketing", level: "Intermediate" },
      { id: "marketing-12", question: "What is 'inbound marketing'?", options: ["A strategy that focuses on attracting customers with content that is relevant and helpful", "A strategy that focuses on paid ads", "A method for cold calling", "A way to send mass emails"], correct: 0, category: "marketing", level: "Intermediate" },
      { id: "marketing-13", question: "What is 'conversion rate'?", options: ["The percentage of visitors to your website who complete a desired action", "The rate at which a customer leaves your website", "The rate at which a product is sold", "The percentage of people who click on your ad"], correct: 0, category: "marketing", level: "Intermediate" },
      { id: "marketing-14", question: "What is 'brand identity'?", options: ["The visual aspects and personality of a brand", "A way to identify a brand", "The legal name of a brand", "The history of a brand"], correct: 0, category: "marketing", level: "Intermediate" },
      { id: "marketing-15", question: "What is `ROI`?", options: ["Return On Investment", "Revenue on Impact", "Return of Interest", "Retention of Investment"], correct: 0, category: "marketing", level: "Intermediate" },
      { id: "marketing-16", question: "What is a 'lead magnet'?", options: ["A marketing tool that offers a valuable piece of content in exchange for a user's contact information", "A tool for generating leads", "A type of paid ad", "A way to attract customers"], correct: 0, category: "marketing", level: "Intermediate" },
      { id: "marketing-17", question: "What is 'content syndication'?", options: ["The process of pushing your content out to third-party sites to reach a wider audience", "A way to create content", "A method for content marketing", "A tool for content analysis"], correct: 0, category: "marketing", level: "Intermediate" },
      { id: "marketing-18", question: "What is 'customer lifetime value' (CLV)?", options: ["A metric that represents the total net profit a company can expect from a single customer over their entire relationship", "A metric that measures how long a customer stays with a company", "A way to measure customer satisfaction", "A metric that measures customer loyalty"], correct: 0, category: "marketing", level: "Intermediate" },
      { id: "marketing-19", question: "What is 'brand equity'?", options: ["The value of a brand based on consumer perception and experience", "The financial value of a brand", "The legal value of a brand", "The brand's market share"], correct: 0, category: "marketing", level: "Intermediate" },
      { id: "marketing-20", question: "What is a 'buyer persona'?", options: ["A fictional representation of your ideal customer based on market research and real data about your existing customers", "A real person who buys your product", "A way to segment your audience", "A tool for market research"], correct: 0, category: "marketing", level: "Intermediate" },
    ],
    Advanced: [
      { id: "marketing-21", question: "Explain the `Porter's Five Forces` model.", options: ["A framework for analyzing a company's competitive environment", "A model for marketing strategy", "A way to segment a market", "A tool for market research"], correct: 0, category: "marketing", level: "Advanced" },
      { id: "marketing-22", question: "What is 'customer segmentation'?", options: ["The process of dividing a broad consumer market into sub-groups based on shared characteristics", "A way to segment a product", "A method for market analysis", "A tool for data analysis"], correct: 0, category: "marketing", level: "Advanced" },
      { id: "marketing-23", question: "What is `cannibalization` in marketing?", options: ["A reduction in sales volume, sales revenue, or market share of one product as a result of the introduction of a new product by the same company", "A way to increase sales", "A method for market research", "A tool for product development"], correct: 0, category: "marketing", level: "Advanced" },
      { id: "marketing-24", question: "What is a `SWOT` analysis?", options: ["A framework for evaluating a company's Strengths, Weaknesses, Opportunities, and Threats", "A way to analyze a market", "A tool for project management", "A method for strategic planning"], correct: 0, category: "marketing", level: "Advanced" },
      { id: "marketing-25", question: "What is 'multi-channel marketing'?", options: ["The practice of using multiple channels to communicate with customers", "A way to sell a product on multiple platforms", "A method for market analysis", "A tool for advertising"], correct: 0, category: "marketing", level: "Advanced" },
      { id: "marketing-26", question: "What is 'permission marketing'?", options: ["A marketing strategy in which a company asks for permission from the user before sending them marketing materials", "A way to get permission to advertise", "A method for cold calling", "A tool for email marketing"], correct: 0, category: "marketing", level: "Advanced" },
      { id: "marketing-27", question: "What is `SEO`'s primary goal?", options: ["To increase a website's visibility in search engine results pages through organic (unpaid) methods", "To get a website on the first page of Google", "To increase website traffic through paid ads", "To improve a website's design"], correct: 0, category: "marketing", level: "Advanced" },
      { id: "marketing-28", question: "What is the difference between `B2B` and `B2C` marketing?", options: ["B2B marketing focuses on selling products or services to other businesses, while B2C focuses on selling directly to consumers", "B2B is for business, B2C is for consumers", "B2B is for big companies, B2C is for small ones", "They are the same"], correct: 0, category: "marketing", level: "Advanced" },
      { id: "marketing-29", question: "What is a `marketing funnel`?", options: ["A model that illustrates the theoretical journey of a customer from awareness to purchase and beyond", "A tool for tracking sales", "A way to organize marketing efforts", "A method for lead generation"], correct: 0, category: "marketing", level: "Advanced" },
      { id: "marketing-30", question: "What is 'content marketing'?", options: ["A marketing strategy of creating and distributing valuable, relevant, and consistent content to attract and retain a clearly defined audience", "A way to sell a product", "A method for advertising", "A tool for social media management"], correct: 0, category: "marketing", level: "Advanced" },
    ],
    Expert: [
      { id: "marketing-31", question: "What is 'disruptive innovation'?", options: ["An innovation that creates a new market and value network, eventually displacing established market-leading firms", "A way to disrupt a market", "A type of marketing strategy", "A tool for product development"], correct: 0, category: "marketing", level: "Expert" },
      { id: "marketing-32", question: "Explain the `Ansoff Matrix`.", options: ["A strategic marketing planning tool that helps businesses grow by identifying four product/market strategies", "A way to analyze a market", "A tool for market research", "A method for product development"], correct: 0, category: "marketing", level: "Expert" },
      { id: "marketing-33", question: "What is 'viral marketing'?", options: ["A marketing technique that uses pre-existing social networking services and other technologies to produce increases in brand awareness or to achieve other marketing objectives", "A way to create a viral video", "A method for advertising", "A tool for social media management"], correct: 0, category: "marketing", level: "Expert" },
      { id: "marketing-34", question: "What is `dark social`?", options: ["Social sharing that happens outside of a website's trackable channels, such as email, text messages, and instant messaging apps", "A way to share content on social media", "A method for social media marketing", "A tool for social media analysis"], correct: 0, category: "marketing", level: "Expert" },
      { id: "marketing-35", question: "Explain 'marketing automation'.", options: ["Software that automates marketing tasks, such as email marketing, social media posting, and ad campaigns", "A way to automate marketing", "A tool for marketing analysis", "A method for lead generation"], correct: 0, category: "marketing", level: "Expert" },
      { id: "marketing-36", question: "What is 'brand architecture'?", options: ["The structure and relationship of a company's portfolio of brands", "A way to design a brand", "A method for branding", "A tool for brand management"], correct: 0, category: "marketing", level: "Expert" },
      { id: "marketing-37", question: "What is 'growth hacking'?", options: ["A marketing technique that uses a combination of data, creativity, and technology to acquire and retain customers", "A way to hack a company's growth", "A method for marketing", "A tool for data analysis"], correct: 0, category: "marketing", level: "Expert" },
      { id: "marketing-38", question: "What is the 'Pareto Principle' in marketing?", options: ["A principle that states that roughly 80% of effects come from 20% of the causes, often applied to customer loyalty and revenue", "A rule for marketing strategy", "A method for market research", "A tool for data analysis"], correct: 0, category: "marketing", level: "Expert" },
      { id: "marketing-39", question: "What is a 'marketing mix'?", options: ["The set of marketing tools (product, price, place, promotion) that a firm uses to pursue its marketing objectives", "A way to mix different marketing strategies", "A method for market research", "A tool for strategic planning"], correct: 0, category: "marketing", level: "Expert" },
      { id: "marketing-40", question: "What is 'marketing myopia'?", options: ["A short-sighted and inward-looking approach to marketing that focuses on fulfilling immediate company needs rather than fulfilling customer needs", "A way to market a product", "A method for market research", "A tool for strategic planning"], correct: 0, category: "marketing", level: "Expert" },
    ],
  },
  data: {
    Beginner: [
      {
        id: "data-1",
        question: "Which measure of central tendency is most robust to outliers?",
        options: ["Mean", "Median", "Mode", "Range"],
        correct: 1,
        category: "data",
        level: "Beginner",
      },
      {
        id: "data-2",
        question: "SQL GROUP BY is used to...",
        options: [
          "Group rows that share values so aggregates can be computed",
          "Sort rows alphabetically",
          "Filter rows before aggregation",
          "Join multiple tables",
        ],
        correct: 0,
        category: "data",
        level: "Beginner",
      },
      {
        id: "data-3",
        question: "Recall measures...",
        options: [
          "Share of actual positives correctly identified",
          "Share of predicted positives that are correct",
          "Overall accuracy",
          "The F1 score",
        ],
        correct: 0,
        category: "data",
        level: "Beginner",
      },
      {
        id: "data-4",
        question: "A correlation coefficient (r) ranges between...",
        options: ["-1 and 1", "0 and 1", "-∞ and ∞", "-10 and 10"],
        correct: 0,
        category: "data",
        level: "Beginner",
      },
      {
        id: "data-5",
        question: "A histogram is best for visualizing...",
        options: [
          "Distribution of a single numeric variable",
          "Relationship between two categorical variables",
          "Time series trending",
          "Geospatial clusters",
        ],
        correct: 0,
        category: "data",
        level: "Beginner",
      },
      {
        id: "data-6",
        question: "Why split data into train/validation/test sets?",
        options: [
          "To estimate performance and tune without overfitting",
          "To increase data volume",
          "To randomize row order",
          "To improve CPU utilization",
        ],
        correct: 0,
        category: "data",
        level: "Beginner",
      },
    ],
    Intermediate: [
      { id: "data-11", question: "What is `SQL JOIN` used for?", options: ["To combine rows from two or more tables based on a related column between them", "To add new rows to a table", "To delete rows from a table", "To update rows in a table"], correct: 0, category: "data", level: "Intermediate" },
      { id: "data-12", question: "What is `feature engineering`?", options: ["The process of using domain knowledge to create features that make machine learning algorithms work better", "A way to create a new feature", "A method for data cleaning", "A tool for data analysis"], correct: 0, category: "data", level: "Intermediate" },
      { id: "data-13", question: "What is `overfitting` in machine learning?", options: ["A model that learns the training data too well, capturing noise and leading to poor performance on new data", "A model that is too simple", "A model that is too complex", "A model that is too slow"], correct: 0, category: "data", level: "Intermediate" },
      { id: "data-14", question: "What is the difference between `classification` and `regression`?", options: ["Classification predicts a categorical outcome, while regression predicts a continuous one", "Classification predicts a continuous outcome, while regression predicts a categorical one", "They are the same", "One is for supervised learning, the other is for unsupervised learning"], correct: 0, category: "data", level: "Intermediate" },
      { id: "data-15", question: "What is a `scatter plot` best for?", options: ["Visualizing the relationship between two numerical variables", "Showing the distribution of a single variable", "Comparing categorical data", "Showing time series data"], correct: 0, category: "data", level: "Intermediate" },
      { id: "data-16", question: "What is the purpose of `normalization` in a database?", options: ["To reduce data redundancy and improve data integrity", "To make data easier to read", "To increase data size", "To speed up data retrieval"], correct: 0, category: "data", level: "Intermediate" },
      { id: "data-17", question: "What is the `p-value` in statistics?", options: ["The probability of obtaining test results at least as extreme as the results actually observed, under the assumption that the null hypothesis is correct", "The probability of an event", "A measure of a model's performance", "A type of statistical test"], correct: 0, category: "data", level: "Intermediate" },
      { id: "data-18", question: "What is `data cleaning`?", options: ["The process of fixing or removing incorrect, corrupted, incorrectly formatted, duplicate, or incomplete data within a dataset", "A way to organize data", "A method for data entry", "A tool for data analysis"], correct: 0, category: "data", level: "Intermediate" },
      { id: "data-19", question: "What is `cross-validation`?", options: ["A technique for evaluating a model's performance on a new dataset by splitting the data into multiple subsets", "A way to validate data", "A method for data cleaning", "A tool for data analysis"], correct: 0, category: "data", level: "Intermediate" },
      { id: "data-20", question: "What is a `time series`?", options: ["A series of data points indexed (or listed or graphed) in time order", "A way to track time", "A type of graph", "A method for data analysis"], correct: 0, category: "data", level: "Intermediate" },
    ],
    Advanced: [
      { id: "data-21", question: "What is the `Central Limit Theorem`?", options: ["A theorem that states that the distribution of sample means approximates a normal distribution as the sample size becomes larger, regardless of the population's distribution", "A theorem about central tendencies", "A law of probability", "A way to find the mean of a dataset"], correct: 0, category: "data", level: "Advanced" },
      { id: "data-22", question: "Explain `Bayes' Theorem`.", options: ["A theorem that describes the probability of an event, based on prior knowledge of conditions that might be related to the event", "A theorem about conditional probability", "A law of statistics", "A way to predict an outcome"], correct: 0, category: "data", level: "Advanced" },
      { id: "data-23", question: "What is a `Z-score`?", options: ["A measure of how many standard deviations below or above the population mean a data point is", "A score for a test", "A way to normalize data", "A type of statistical test"], correct: 0, category: "data", level: "Advanced" },
      { id: "data-24", question: "Explain the difference between `Precision` and `Recall`.", options: ["Precision is the ratio of correctly predicted positive observations to the total predicted positive observations. Recall is the ratio of correctly predicted positive observations to all observations in the actual class.", "They are the same", "One is for classification, the other for regression", "One is a measure of accuracy, the other is a measure of completeness"], correct: 0, category: "data", level: "Advanced" },
      { id: "data-25", question: "What is a `ROC Curve`?", options: ["A graph showing the performance of a classification model at all classification thresholds", "A type of graph", "A way to measure a model's performance", "A tool for data visualization"], correct: 0, category: "data", level: "Advanced" },
      { id: "data-26", question: "What is a `Confusion Matrix`?", options: ["A table that is often used to describe the performance of a classification model on a set of test data for which the true values are known", "A way to confuse a user", "A tool for data visualization", "A method for data analysis"], correct: 0, category: "data", level: "Advanced" },
      { id: "data-27", question: "Explain `sampling bias`.", options: ["A bias in which a sample is collected in such a way that some members of the intended population are less likely to be included than others", "A way to bias a model", "A method for data analysis", "A tool for data cleaning"], correct: 0, category: "data", level: "Advanced" },
      { id: "data-28", question: "What is `principal component analysis` (PCA)?", options: ["A statistical procedure that uses an orthogonal transformation to convert a set of observations of possibly correlated variables into a set of values of linearly uncorrelated variables", "A way to analyze a product's performance", "A tool for data visualization", "A method for data cleaning"], correct: 0, category: "data", level: "Advanced" },
      { id: "data-29", question: "What is `regularization` in machine learning?", options: ["A technique used to reduce overfitting by adding a penalty to the model's complexity", "A way to regularize a model", "A method for data cleaning", "A tool for data analysis"], correct: 0, category: "data", level: "Advanced" },
      { id: "data-30", question: "Explain `F-score`.", options: ["A measure of a model's accuracy on a dataset, which combines precision and recall", "A score for a test", "A way to measure a model's performance", "A tool for data visualization"], correct: 0, category: "data", level: "Advanced" },
    ],
    Expert: [
      { id: "data-31", question: "Explain `Bayesian inference`.", options: ["A method of statistical inference in which Bayes' theorem is used to update the probability for a hypothesis as more evidence or information becomes available", "A way to infer a conclusion", "A method for data analysis", "A tool for statistical analysis"], correct: 0, category: "data", level: "Expert" },
      { id: "data-32", question: "What is `Gibbs sampling`?", options: ["A Markov chain Monte Carlo (MCMC) algorithm for obtaining a sequence of observations which are approximated from a specified multivariate probability distribution", "A way to sample data", "A method for statistical analysis", "A tool for data analysis"], correct: 0, category: "data", level: "Expert" },
      { id: "data-33", question: "Explain `Eigenvalues` and `Eigenvectors` in data analysis.", options: ["In PCA, they are used to determine the principal components and the variance they capture, respectively", "A way to analyze data", "A method for statistical analysis", "A tool for data analysis"], correct: 0, category: "data", level: "Expert" },
      { id: "data-34", question: "What is `L1 and L2 regularization`?", options: ["L1 (Lasso) adds a penalty equal to the absolute value of the magnitude of coefficients, while L2 (Ridge) adds a penalty equal to the square of the magnitude of coefficients", "A way to normalize data", "A method for data cleaning", "A tool for data analysis"], correct: 0, category: "data", level: "Expert" },
      { id: "data-35", question: "Explain the `Bias-Variance` tradeoff.", options: ["The balance between a model's tendency to consistently make the same error (bias) and its tendency to make inconsistent errors (variance)", "A way to balance a model", "A method for model analysis", "A tool for model training"], correct: 0, category: "data", level: "Expert" },
      { id: "data-36", question: "What is `Monte Carlo simulation`?", options: ["A broad class of computational algorithms that rely on repeated random sampling to obtain numerical results", "A way to simulate data", "A method for statistical analysis", "A tool for data analysis"], correct: 0, category: "data", level: "Expert" },
      { id: "data-37", question: "What is a `kernel` in a Support Vector Machine (SVM)?", options: ["A function that takes low-dimensional input and transforms it into a higher-dimensional space, making it easier to separate classes", "A way to classify data", "A method for model training", "A tool for data analysis"], correct: 0, category: "data", level: "Expert" },
      { id: "data-38", question: "Explain `Ensemble Learning`.", options: ["A method where multiple models (weak learners) are trained to solve the same problem and combined to get a better result", "A way to learn from an ensemble", "A method for model training", "A tool for data analysis"], correct: 0, category: "data", level: "Expert" },
      { id: "data-39", question: "What is a `Chi-Squared` test?", options: ["A statistical test used to determine if there is a significant association between two categorical variables", "A way to test a model's performance", "A method for statistical analysis", "A tool for data analysis"], correct: 0, category: "data", level: "Expert" },
      { id: "data-40", question: "What is a `T-test`?", options: ["A statistical test used to determine if there is a significant difference between the means of two groups", "A way to test a model's performance", "A method for statistical analysis", "A tool for data analysis"], correct: 0, category: "data", level: "Expert" },
    ],
  },
};

// helper shuffle
function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

// ambil N soal acak untuk skill tertentu
export function getQuestionsBySkill(
  skillId: string,
  level: AssessmentLevel,
  count?: number
): Question[] {
  const pool = BANK[skillId]?.[level] ?? [];
  const questionCount = count ?? 10;

  if (pool.length <= questionCount) {
    return [...pool];
  }
  return shuffle(pool).slice(0, questionCount);
}

// opsional: list skill yang tersedia
export const SKILL_IDS = Object.keys(BANK);

// (opsional) export BANK jika butuh akses penuh di tempat lain
export { BANK };